databases:
  - name: trythis_DB
    databaseName: trythis_db
    user: trythis
    region: singapore

services:
  - type: web
    name: trythis
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trythis_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

